#bin/bash
erl -compile isis ledger
erl -setcookie wermer -sname a -noshell -detached -eval 'isis:p("a@DESKTOP-JHAH5MV"), ledger:start(), lists:foreach(fun (_) -> ledger:ledgerAppend("data") end, lists:seq(1, 500)), io:format("~p", [length(ledger:ledgerGet())])'
erl -setcookie wermer -sname b -noshell -detached -eval 'isis:p("a@DESKTOP-JHAH5MV"), ledger:start(), lists:foreach(fun (_) -> ledger:ledgerAppend("data") end, lists:seq(1, 1000)), io:format("~p", [length(ledger:ledgerGet())])'
erl -setcookie wermer -sname c -noshell -detached -eval 'isis:p("a@DESKTOP-JHAH5MV"), ledger:start(), lists:foreach(fun (_) -> ledger:ledgerAppend("data") end, lists:seq(1, 1000)), io:format("~p", [length(ledger:ledgerGet())])'
erl -setcookie wermer -sname d -noshell -detached -eval 'isis:p("a@DESKTOP-JHAH5MV"), ledger:start(), lists:foreach(fun (_) -> ledger:ledgerAppend("data") end, lists:seq(1, 1000)), io:format("~p", [length(ledger:ledgerGet())])'
erl -setcookie wermer -sname e -noshell -detached -eval 'isis:p("a@DESKTOP-JHAH5MV"), ledger:start(), lists:foreach(fun (_) -> ledger:ledgerAppend("data") end, lists:seq(1, 1000)), io:format("~p", [length(ledger:ledgerGet())])'
erl -setcookie wermer -sname f -noshell -detached -eval 'isis:p("a@DESKTOP-JHAH5MV"), ledger:start(), lists:foreach(fun (_) -> ledger:ledgerAppend("data") end, lists:seq(1, 1000)), io:format("~p", [length(ledger:ledgerGet())])'
erl -setcookie wermer -sname g -noshell -detached -eval 'isis:p("a@DESKTOP-JHAH5MV"), ledger:start(), lists:foreach(fun (_) -> ledger:ledgerAppend("data") end, lists:seq(1, 1000)), io:format("~p", [length(ledger:ledgerGet())])'
erl -setcookie wermer -sname h -eval 'isis:p("a@DESKTOP-JHAH5MV"), ledger:start(), lists:foreach(fun (_) -> ledger:ledgerAppend("data") end, lists:seq(1, 1000)), io:format("~p", [length(ledger:ledgerGet())]), q()'